stages:
  - build

push-phishing-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-phishing-image.sh

push-navigation-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-navigation-image.sh

build-python-service:
  stage: build
  image: registry.code.fbi.h-da.de/esc-mpse20/container-templates/python-windows-service-builder:python-service-buzilder
  script: 
    - ls -la
    - pwd
    - cd ./native
    - ls -l
    - bash ./entrypoint-windows.sh
  artifacts:
    paths:
      - /builds/esc-mpse20/demonstrations/native/native/dist/windows/*

push-password-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-password-image.sh
