stages:
  - build

push-demo-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-phishing-image.sh

push-navigation-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-navigation-image.sh

build-python-service:
  stage: build
  image: cdrx/pyinstaller-windows
  script: 
    - ln -s /native /src
    - cd /src
    - ls -la
    - sh /src/entrypoint-windows.sh
  artifacts:
    paths:
      - dist/windows/*
