stages:
  - linting
  - build

lint-python-code:
  stage: linting
  image:
    name: python:3.9-slim
  before_script:
    - python -m pip install flake8
  script:
    - flake8 .
  allow_failure: true

push-phishing-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-phishing-image.sh

push-navigation-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sed -i "s|replacedByCi|$TEACHING_URL|" "Demo Navigation/config/prod.env.js"
    - cat "Demo Navigation/config/prod.env.js"
    - sh ./ci/push-navigation-image.sh

build-python-service:
  stage: build
  image: $REGISTRY_URL/$GROUP_NAME/container-templates/python-windows-service-builder:python-service-buzilder
  script: 
    - cd ./native/msi
    - echo "" >> infos.rtf
    - echo "\pard\sl240\slmult1\f1\fs18 > docker login $REGISTRY_URL\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/navigation:master\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/phishing:master\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/password:master\par" >> infos.rtf
    - echo "}" >> infos.rtf
    - cd ..
    - ls -la
    - pwd
    - bash ./entrypoint-windows.sh $GROUP_NAME
  artifacts:
    paths:
      - /builds/$GROUP_NAME/demonstrations/native/native/dist/windows/*
      - /builds/$GROUP_NAME/demonstrations/native/msi/infos.rtf

push-password-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-password-image.sh
