stages:
  - generate
  - lint
  - test
  - demo
  - release

variables:
  # Package version can only contain numbers (0-9), and dots (.).
  # Must be in the format of X.Y.Z, i.e. should match /\A\d+\.\d+\.\d+\z/ regular expresion.
  # See https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nativeapp/${CI_COMMIT_TAG}"
  ZIP: "nativeapp-${CI_COMMIT_TAG}.zip"
  SUB_PROJECT_DOCKERFILE: Dockerfile

lint:shell-code:
  stage: lint
  image: koalaman/shellcheck-alpine:stable
  script:
    - shellcheck -x init_new_demo.sh
  needs: []

lint:python-code:
  stage: lint
  image:
    name: python:3.10-slim
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - python -m pip install flake8
  script:
    - flake8 .
  needs: []

sast:python-code:
  stage: lint
  image:
    name: python:3.9-slim
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - python -m pip install bandit
  script:
    - bandit -r . -ll
  allow_failure: true
  needs: []

test:python:
  stage: test
  image: python:3.7
  script:
    - cd native
    - pip install -r nativeapp/requirements.txt
    - python -m unittest


release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG


pages:
  stage: release
  image: alpine:edge
  script:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> "/etc/apk/repositories"
    - apk update && apk add mdbook
    - mkdir -p public/$CI_COMMIT_REF_NAME
    - sh -c "[ $CI_COMMIT_REF_NAME == 'develop' ] && mdbook build mdbook -d ../public || true"
    - mdbook build mdbook -d ../public/$CI_COMMIT_REF_NAME
  artifacts:
    name: "demonstrations"
    paths:
      - public
  # Cache pages to enable
  cache:
    key: "doc"
    paths:
      - public
  only:
    - develop


generate-demo-jobs:
  stage: generate
  image: alpine
  script:
    - apk update && apk add python3
    - python3 generate_ci_jobs.py
  artifacts:
    paths:
      - generated_demo_ci.yml
      - generated_license_ci.yml

license-jobs:
  stage: test
  trigger:
    include:
      - artifact: generated_license_ci.yml
        job: generate-demo-jobs
    strategy: depend

demo-image-jobs:
  stage: demo
  trigger:
    include:
      - artifact: generated_demo_ci.yml
        job: generate-demo-jobs
    strategy: depend
