stages:
  - linting
  - build
  - scan
  - push

lint-python-code:
  stage: linting
  image:
    name: python:3.9-slim
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - python -m pip install flake8
  script:
    - flake8 .
  allow_failure: true

sast-python-code:
  stage: linting
  image:
    name: python:3.9-slim
  before_script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - python -m pip install bandit
  script:
    - bandit -r .
  allow_failure: true

push-navigation-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sed -i "s|replacedByCi|$TEACHING_URL|" "demo_navigation/config/prod.env.js"
    - sh ./ci/push-navigation-image.sh

build-python-service:
  stage: build
  image: $REGISTRY_URL/$GROUP_NAME/container-templates/python-windows-service-builder:python-service-buzilder
  script: 
    - cd ./native/msi
    - echo "" >> infos.rtf
    - echo "\pard\sl240\slmult1\f1\fs18 > docker login $REGISTRY_URL\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/navigation:master\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/phishing:master\par" >> infos.rtf
    - echo "> docker pull $REGISTRY_URL/$GROUP_NAME/demonstrations/password:master\par" >> infos.rtf
    - echo "}" >> infos.rtf
    - cd ..
    - ls -la
    - pwd
    - bash ./entrypoint-windows.sh $GROUP_NAME
  artifacts:
    paths:
      - /builds/$GROUP_NAME/demonstrations/native/native/dist/windows/*
      - /builds/$GROUP_NAME/demonstrations/native/msi/infos.rtf

push-password-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh ./ci/push-password-image.sh

build-phishing-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "starting karniko docker build for phishing Image"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - image_name="$CI_REGISTRY_IMAGE/phishing:$CI_COMMIT_BRANCH"
    - echo "pushing to $image_name"
    - /kaniko/executor 
      --build-arg REGISTRY_URL=$REGISTRY_URL 
      --build-arg GROUP_NAME=$GROUP_NAME 
      --context "$CI_PROJECT_DIR/phishing_demo/" 
      --dockerfile "$CI_PROJECT_DIR/phishing_demo/Dockerfile" 
      --destination "$image_name"
      --no-push
      --tarPath phishing_image.tar
  artifacts:
    paths:
    - phishing_image.tar
    when: on_success

scan-phishing-image:
  stage: scan
  image:
    name: aquasec/trivy:latest
  allow_failure: true
  script:
    # Build report
    - trivy 
      --exit-code 0 
      --cache-dir .trivycache/ 
      --no-progress 
      --format template 
      --template "@contrib/gitlab.tpl" 
      -o gl-container-scanning-report.json 
      --input phishing_image.tar
    # Print report
    - trivy 
      --exit-code 0 
      --cache-dir .trivycache/ 
      --no-progress 
      --severity HIGH 
      --input phishing_image.tar
    # Fail on high and critical vulnerabilities
    - trivy 
      --exit-code 1 
      --cache-dir .trivycache/ 
      --severity CRITICAL 
      --no-progress 
      --input phishing_image.tar
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  needs:
  - build-phishing-image
  
push-phishing-image:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
  - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - crane push phishing_image.tar $CI_REGISTRY_IMAGE/phishing:$CI_COMMIT_BRANCH
  needs:
  - scan-phishing-image

