version: '3.7'

services:
  password:
    image: ${REGISTRY_URL}/${GROUP_NAME}/demonstrations/${HDA_PASSWORD_REPO}
    container_name: hda_password_webserver
    ports:
      - "5001:5001"
  nginx:
    image: ${REGISTRY_URL}/${GROUP_NAME}/demonstrations/${HDA_PASSWORD_NGINX_REPO}
    container_name: hda_password_nginx_server
    ports:
      - "443:443"

# services:
#   password:
#     build:
#       context: ./demos/hda_password/
#     container_name: hda_password_webserver
#     ports:
#       - "5001:5001"
#   redis:
#     image: "redis:alpine"
#   nginx:
#     build:
#       context: ./demos/hda_password/src/nginx/
#     container_name: hda_password_nginx_server
#     ports:
#       - "443:443"