// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.fission.experiment.enrollmentStatus", 4);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "3e7ff867-1cd1-4ad1-9ce5-8e3272c8a199");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"app.update.background.enabled=false\",\"not default profile\"]");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1641988427);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1641988454);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{4d8c111c-c439-45b9-a999-7591bf71279c}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1641988424);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 120);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"116604\":1641988454312,\"116639\":1641988454310,\"116238120\":1641988454311}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"108197805\":[1641988454311]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{bad1a67b-2ef4-4572-ae02-546179ca6d48}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1641988426);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1641988440881");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1641990242881");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1641988428688");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1642010028688");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20211218203254");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1641988454");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20211218203254");
user_pref("browser.startup.homepage_override.mstone", "95.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1641988454);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 1);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1641988426379");
user_pref("distribution.iniFile.exists.appversion", "95.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.push.userAgentID", "e3bf2290b60c4be7a965f32f2cfa3983");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211218203254");
user_pref("extensions.lastAppVersion", "95.0.2");
user_pref("extensions.lastPlatformVersion", "95.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"5d704a78-2609-4735-818f-d5185296fb71\",\"formautofill@mozilla.org\":\"a03764bf-3d93-46d1-8b17-c4a9d5a1fb9d\",\"pictureinpicture@mozilla.org\":\"e922b4ce-55d0-4887-98c6-822263846752\",\"proxy-failover@mozilla.com\":\"a5539e3c-137b-463a-bdca-a34603f37105\",\"screenshots@mozilla.org\":\"f348c2e2-dd10-4951-a121-708c0c49d8f5\",\"webcompat-reporter@mozilla.org\":\"51a83fc1-7a4a-4aa6-ab9b-1a1756db3c28\",\"webcompat@mozilla.org\":\"2c7b33d5-e6c2-4f37-8ce7-f30169443911\",\"default-theme@mozilla.org\":\"91204af2-5bbd-4cad-b268-32816b91c7a6\",\"addons-search-detection@mozilla.com\":\"74c016d1-9b07-4bc3-88ea-4f3eff2a1995\",\"google@search.mozilla.org\":\"b1794c32-8a27-411c-a9d7-e442ec643152\",\"leo_ende_de@search.mozilla.org\":\"6a52f25b-8e65-428d-b719-c250954db1f6\",\"ecosia@search.mozilla.org\":\"68986e57-b515-40b7-aa1f-f51fc6642787\",\"wikipedia@search.mozilla.org\":\"e18a8e6c-36e6-420b-ac2a-a5c9dd59ac0f\",\"bing@search.mozilla.org\":\"bb4f7bdf-fbfd-44e2-b273-656acccb3dbc\",\"ddg@search.mozilla.org\":\"8294ef19-62ae-4abc-b5c4-3a5443779a58\",\"ebay@search.mozilla.org\":\"8790e144-4cf5-4b81-88a7-696698c4552b\",\"amazon@search.mozilla.org\":\"67dbd9f1-ccf6-4bd1-819e-440e2172b131\",\"uBlock0@raymondhill.net\":\"d081dd0d-6c0d-4325-ad13-dbcbc5f00bfe\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1641988426);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("fission.experiment.startupEnrollmentStatus", 4);
user_pref("gfx-shader-check.build-version", "20211218203254");
user_pref("gfx-shader-check.device-id", "0x1c82");
user_pref("gfx-shader-check.driver-version", "27.21.14.6611");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x1c82");
user_pref("sanity-test.driver-version", "27.21.14.6611");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20211218203254");
user_pref("security.sandbox.content.tempDirSuffix", "{8915a71a-b005-4e3a-8f24-35ccf3ff8f67}");
user_pref("toolkit.startup.last_success", 1641988453);
user_pref("toolkit.telemetry.cachedClientID", "3774fd2f-ea37-4808-b685-d83914446632");
user_pref("toolkit.telemetry.previousBuildID", "20211218203254");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
