// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.fission.experiment.enrollmentStatus", 4);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "06f4d9f6-0c06-4985-b2c7-11d51b109b6a");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"app.update.background.enabled=false\",\"not default profile\"]");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1641988322);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1641988321);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{7fefec78-0f97-4bb3-89c6-953d371d0ef8}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1641988318);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 120);
user_pref("browser.newtabpage.activity-stream.impressionId", "{86f30238-bcc7-41d4-bd83-0a1c85de6750}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1641988321);
user_pref("browser.search.region", "DE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1641988320");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20211218203254");
user_pref("browser.startup.homepage_override.mstone", "95.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1641988320);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 1);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1641988320838");
user_pref("distribution.iniFile.exists.appversion", "95.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.push.userAgentID", "377a339cd3354987aaa8f8dee46923dc");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211218203254");
user_pref("extensions.lastAppVersion", "95.0.2");
user_pref("extensions.lastPlatformVersion", "95.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"341b979d-b3e5-4e40-90ba-2a836fbdf1e8\",\"formautofill@mozilla.org\":\"a3f9df0a-7563-4171-8fed-7f24d01f468f\",\"pictureinpicture@mozilla.org\":\"f920e200-cbac-4f66-b0a1-cba32b9c0e29\",\"proxy-failover@mozilla.com\":\"edeb7770-ce1a-4ce1-a4c4-a2a5eb778f53\",\"screenshots@mozilla.org\":\"668be00b-fd70-4983-bc86-0568773385af\",\"webcompat-reporter@mozilla.org\":\"be4de88a-b2a1-47bf-b521-f3addb8332df\",\"webcompat@mozilla.org\":\"8ffad482-fa74-4706-ac11-25bb76bd2ce7\",\"default-theme@mozilla.org\":\"b633c9df-2e54-4127-8a4e-ab9605f112b6\",\"addons-search-detection@mozilla.com\":\"9aaadd7a-58a5-4617-b76f-d44b1bba1738\",\"google@search.mozilla.org\":\"afb28fe1-5771-488a-8db5-e32a582eb9de\",\"leo_ende_de@search.mozilla.org\":\"b700f12c-97d3-4086-bf30-729500b28247\",\"ecosia@search.mozilla.org\":\"4c8db264-ebc2-48c1-9213-235769865be7\",\"wikipedia@search.mozilla.org\":\"4c9c4e45-388a-46b6-b8b3-56076917a36c\",\"bing@search.mozilla.org\":\"9d9d77e4-2c42-48d4-b8e8-3b2eebc30018\",\"ddg@search.mozilla.org\":\"45d206f5-4fd4-46bd-a807-2088a119c484\",\"ebay@search.mozilla.org\":\"cd1222b7-7565-458d-a0f0-488e9c264cce\",\"amazon@search.mozilla.org\":\"eddd04aa-b779-4c5c-b90b-35be2bbf3178\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1641988320);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("fission.experiment.startupEnrollmentStatus", 4);
user_pref("gfx-shader-check.build-version", "20211218203254");
user_pref("gfx-shader-check.device-id", "0x1c82");
user_pref("gfx-shader-check.driver-version", "27.21.14.6611");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x1c82");
user_pref("sanity-test.driver-version", "27.21.14.6611");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20211218203254");
user_pref("security.sandbox.content.tempDirSuffix", "{abf3bf3b-49fb-49aa-8e55-e2a2496b13e1}");
user_pref("toolkit.startup.last_success", 1641988318);
user_pref("toolkit.telemetry.cachedClientID", "17fdeabc-7c96-44fd-9054-4cb8aafed06b");
user_pref("toolkit.telemetry.previousBuildID", "20211218203254");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
