version: '3.9'

services:
  phishing:
    #  image: ${REGISTRY_URL}/${GROUP_NAME}/demonstrations/${FOKUSRNWARE_REPO}
    #  container_name: fokusrnware_webserver
    #  ports:
    #    - 443:443
    build:
      context: ../../../fokusrnware/
    container_name: phishing_webserver
    ports:
      - 443:443
  mail:
    image: mailserver/docker-mailserver:10.5.0
    hostname: mail
    domainname: domain.com
    container_name: phishing_mailserver
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mailserver/config/ssl:/tmp/ssl:ro
      # we want to comment this out. otherwise the mail storage is persistent and not "fresh" after restaring the demo
      #- maildata:/var/mail
      #- mailstate:/var/mail-state
      #- maillogs:/var/log/mail
      - ./mailserver/config/:/tmp/docker-mailserver/
    env_file:
      - ./mailserver/mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/mail.domain.com.crt
      - SSL_KEY_PATH=/tmp/ssl/mail.domain.com.key
